version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: robocop
    networks:
      - web
networks:
  backend:
  web:
