version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      -e POSTGRES_USER=discourse -e POSTGRES_DB=discourse -e POSTGRES_PASSWORD=discourse
    networks:
      - web
  discourse:
    image: libresh/discourse:v2.5.0
    restart: always
    ports:
      - 80:5000
    networks:
      - web
      - backend
networks:
  backend:
  web:
